Finalizando pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,5 @@
-echo "Running lint..."
+ echo "Checking for linting errors..."
 
- npx lint-staged
+ npx lint-staged || (echo "Linting errors  or test failed. Please fix them before committing." && exit 1)
+
+ echo "Linting and testing passed. Committing..."
